# Generated by Django 4.1.3 on 2023-06-16 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("status", models.BooleanField(default=False)),
                ("cause", models.TextField()),
                ("symptom", models.TextField()),
                ("precautions", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Pesticide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("producer", models.CharField(max_length=100)),
                ("price", models.BigIntegerField()),
                ("quantity", models.IntegerField()),
                ("thumbnail", models.ImageField(upload_to="static/pesticides")),
            ],
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="static/plants")),
            ],
        ),
        migrations.CreateModel(
            name="PesticideImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="static/pesticides")),
                (
                    "pesticide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PlantDP.pesticide",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pesticide",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="PlantDP.plant"
            ),
        ),
        migrations.CreateModel(
            name="DiseaseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="static/diseases")),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="PlantDP.disease",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="disease",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="PlantDP.plant"
            ),
        ),
    ]
