# Generated by Django 4.1.3 on 2023-06-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PlantDP", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="disease",
            name="status",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="plant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/plants"),
        ),
    ]
