# Generated by Django 4.1.3 on 2023-06-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PlantDP", "0002_remove_product_quantity_alter_disease_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="producer",
            new_name="brand",
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="diseaseimage",
            name="image",
            field=models.ImageField(upload_to="diseases"),
        ),
        migrations.AlterField(
            model_name="plant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="plants"),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(upload_to="products"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.URLField(max_length=256),
        ),
    ]
