# Generated by Django 4.1.3 on 2023-06-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserProfile", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
