# Generated by Django 4.1.3 on 2023-06-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserProfile", "0003_alter_customuser_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="predicthistory",
            old_name="predict",
            new_name="disease",
        ),
        migrations.AddField(
            model_name="predicthistory",
            name="image",
            field=models.ImageField(default=1, max_length=256, upload_to="predicts"),
            preserve_default=False,
        ),
    ]
